language java
install true


dist trusty
jdk
  - openjdk13
  - openjdk-ea


matrix
  allow_failures
    - jdk openjdk-ea

branches
  only
  - master
  - 7.6
    

script
  - .gradlew --continue clean build --scan -s -p modules
